apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-app
  labels:
    app: monitoring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring-app
  template:
    metadata:
      labels:
        app: monitoring-app
    spec:
      containers:
      - name: monitoring-app
        image: docker.io/akshay398/monitoring-app:latest
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: monitoring-app-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: monitoring-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000